projects:
  - 
    name: Popolazione del Comune
    short_name: Popolazione
    description: "Un progetto che riguarda la popolazione del Comune."
    documents:
      - anagrafe-docs
      - altra-anagrafe-docs
  - 
    name: Test Piano triennale ICT
    short_name: Piano triennale
    description: "Test del documento del Piano triennale con il nuovo tema."
    documents:
      - nomedocumento-docs
