projects:
  - title: Popolazione del Comune
    short-name: Popolazione
    description: |
      Un progetto che riguarda la popolazione del Comune.
    website: progetto.ministerodocumentazione.gov.it
    documents:
      - title: Anagrafe
        repository: anagrafe-docs
