projects:
  - title: Popolazione del Comune
    short-name: Popolazione
    description: |
      Un progetto che riguarda la popolazione del Comune.
    website: progetto.ministerodocumentazione.gov.it
    documents:
      - anagrafe-docs
  - title: Test Piano triennale ICT
    short-name: Piano triennale
    description: |
      Test del documento del Piano triennale con il 
      nuovo tema.
    documents:
      - nomedocumento-docs
