publisher:
  name: Città metropolitana di Amba Rabà
  short-name: Amba Rabà
  description: |
    Una città inventata nelle colline del Piovasco.
  github_organization_url: github.com/citta-metropolitana-amba-raba
  assets:
    logo: assets/images/logo.svg
